# Generated by Django 5.0.6 on 2024-06-25 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_rename_user_id_competitionmodels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodels',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='competitionmodels',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competitionmodels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competitionmodels',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
