# Generated by Django 5.0.6 on 2024-06-24 11:00

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_created_at_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
