# Generated by Django 5.0.6 on 2024-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_by',
            field=models.CharField(null=True),
        ),
    ]
