# Generated by Django 5.0.6 on 2024-06-24 11:11
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, null=True),
        ),
    ]
